name: CI Workflow Demo

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint: 
    uses: githubabcs/gh-abcs-actions/.github/workflows/super-linter.yml@main

  ci:
    name: CI
    runs-on: ${{ matrix.os }} 
    needs: lint
    strategy:
      fail-fast: true 
      matrix:
        node-version: [12, 14, 16]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Setup node ${{ matrix.node-version }} 
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }} 
       - name: Run test suite
         run: |
           echo npm ci 
           echo npm run build --if-present 
           echo npm test
      
       - shell: bash
         run: |
          echo 'Test upload artifact' > output.log
       - name: Upload output file
         uses: actions/upload-artifact@v4
         with:
          name: output-log-file
          path: output.log
          
  deploy-test:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: TEST
      url: https://test.company.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file

          
      
          
        
    
